/// Flutter icons Report_Icons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Report_Icons
///      fonts:
///       - asset: fonts/Report_Icons.ttf
///
///
///
// ignore_for_file: camel_case_types, constant_identifier_names

import 'package:flutter/widgets.dart';

class Report_Icons {
  Report_Icons._();

  static const _kFontFam = 'Report_Icons';
  static const String? _kFontPkg = null;

  static const IconData icon_disaster =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_traffic_accident =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_robber =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_lightning_bolt =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_construction =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
